# ── Configurações da Aplicação ──────────────────────────────────────────────
spring.application.name=viagens-api
server.port=8080

# Formata JSON com indentação para facilitar a leitura durante testes
spring.jackson.serialization.indent-output=true

# Retorna o timestamp de erros no formato ISO-8601
spring.jackson.serialization.write-dates-as-timestamps=false
